// src/lib/components/dashboard/RecentSessions.svelte
<script lang="ts">
	import type { SessionWithProject } from '$lib/types/db';
	import { timeAgo } from '$lib/utils';

	let { sessions }: { sessions: SessionWithProject[] } = $props();

	function shortModel(model: string | null): string {
		if (!model) return '';
		return model.replace('claude-', '').split('-').slice(0, 2).join('-');
	}
</script>

<div class="rounded-lg border bg-card text-card-foreground shadow-sm">
	<div class="p-4 pb-2">
		<h3 class="text-base font-semibold">Recent Conversations</h3>
	</div>
	<div class="px-4 pb-4">
		<div class="space-y-1">
			{#each sessions as s (s.id)}
				<a
					href="/conversations/{s.id}"
					class="flex items-center gap-3 px-3 py-2 rounded-md hover:bg-accent transition-colors"
				>
					<div class="flex-1 min-w-0">
						<p class="text-sm font-medium truncate">
							{s.custom_title || s.first_prompt || s.id}
						</p>
						<p class="text-xs text-muted-foreground">
							{s.project_display_name}
						</p>
					</div>
					<div class="flex items-center gap-2 shrink-0">
						{#if s.model}
							<span class="inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-normal text-muted-foreground">
								{shortModel(s.model)}
							</span>
						{/if}
						<span class="text-xs text-muted-foreground w-16 text-right">
							{s.message_count} msgs
						</span>
						<span class="text-xs text-muted-foreground w-16 text-right">
							{timeAgo(s.modified_at)}
						</span>
					</div>
				</a>
			{/each}
			{#if sessions.length === 0}
				<p class="text-sm text-muted-foreground py-4 text-center">
					No conversations found. Run the sync first.
				</p>
			{/if}
		</div>
	</div>
</div>

// web/src/components/dashboard/recent-sessions.tsx
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { SessionWithProject } from "@/types/db";

function timeAgo(dateStr: string | null): string {
  if (!dateStr) return "";
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

export function RecentSessions({
  sessions,
}: {
  sessions: SessionWithProject[];
}) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Recent Conversations</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-1">
          {sessions.map((s) => (
            <Link
              key={s.id}
              href={`/conversations/${s.id}`}
              className="flex items-center gap-3 px-3 py-2 rounded-md hover:bg-accent transition-colors group"
            >
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate">
                  {s.custom_title || s.first_prompt || s.id}
                </p>
                <p className="text-xs text-muted-foreground">
                  {s.project_display_name}
                </p>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                {s.model && (
                  <Badge variant="secondary" className="text-[10px] font-normal">
                    {s.model.replace("claude-", "").split("-").slice(0, 2).join("-")}
                  </Badge>
                )}
                <span className="text-xs text-muted-foreground w-16 text-right">
                  {s.message_count} msgs
                </span>
                <span className="text-xs text-muted-foreground w-16 text-right">
                  {timeAgo(s.modified_at)}
                </span>
              </div>
            </Link>
          ))}
          {sessions.length === 0 && (
            <p className="text-sm text-muted-foreground py-4 text-center">
              No conversations found. Run the sync first.
            </p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
