// web/src/components/layout/sync-button.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

export function SyncButton() {
  const [syncing, setSyncing] = useState(false);
  const router = useRouter();

  async function handleSync() {
    setSyncing(true);
    try {
      await fetch("/api/sync", { method: "POST" });
      router.refresh();
    } finally {
      setSyncing(false);
    }
  }

  return (
    <Button
      variant="ghost"
      size="sm"
      className="h-7 px-2 text-[11px] cursor-pointer"
      onClick={handleSync}
      disabled={syncing}
      title="Re-sync conversations from ~/.claude"
    >
      {syncing ? "Syncing..." : "Sync"}
    </Button>
  );
}

// tauri/src/lib/components/layout/SyncButton.svelte
<script lang="ts">
	import { invalidateAll } from '$app/navigation';
	import { startSync, isSyncing } from '$lib/stores/sync.svelte';

	async function handleSync() {
		await startSync();
		await invalidateAll();
	}
</script>

<button
	onclick={handleSync}
	disabled={isSyncing()}
	title="Re-sync conversations from ~/.claude"
	class="h-7 px-2 text-[11px] rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground disabled:opacity-50 cursor-pointer"
>
	{isSyncing() ? 'Syncing...' : 'Sync'}
</button>
