// src/lib/components/search/SearchForm.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';

	let { defaultValue = '' }: { defaultValue?: string } = $props();
	let query = $derived(defaultValue);

	function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (query.trim()) {
			goto(resolve(`/search?q=${encodeURIComponent(query.trim())}`));
		}
	}
</script>

<form onsubmit={handleSubmit} class="flex gap-2">
	<input
		bind:value={query}
		placeholder="Search across all conversations..."
		class="border-input bg-background h-9 flex-1 rounded-md border px-3 text-sm"
	/>
	<button
		type="submit"
		class="bg-primary text-primary-foreground hover:bg-primary/90 h-9 rounded-md px-4 text-sm font-medium"
	>
		Search
	</button>
</form>

// web/src/components/search/search-form.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function SearchForm({ defaultValue }: { defaultValue: string }) {
  const router = useRouter();
  const [query, setQuery] = useState(defaultValue);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (query.trim()) {
      router.push(`/search?q=${encodeURIComponent(query.trim())}`);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="flex gap-2">
      <Input
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search across all conversations..."
        className="flex-1"
        autoFocus
      />
      <Button type="submit">Search</Button>
    </form>
  );
}
