// web/src/app/conversations/[sessionId]/page.tsx
import { notFound } from "next/navigation";
import { getSession } from "@/lib/actions/sessions";
import { getSessionMessages } from "@/lib/actions/messages";
import { SessionHeader } from "@/components/viewer/session-header";
import { MessageThread } from "@/components/viewer/message-thread";

interface Props {
  params: Promise<{ sessionId: string }>;
}

export default async function ConversationViewerPage({ params }: Props) {
  const { sessionId } = await params;
  const [session, result] = await Promise.all([
    getSession(sessionId),
    getSessionMessages({ sessionId, limit: 500 }),
  ]);

  if (!session) notFound();

  return (
    <div className="flex flex-col h-full">
      <SessionHeader session={session} />
      <MessageThread messages={result.messages} />
    </div>
  );
}

// tauri/src/routes/conversations/[sessionId]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { getSession } from '$lib/api/sessions';
	import { getSessionMessages } from '$lib/api/messages';
	import SessionHeader from '$lib/components/viewer/SessionHeader.svelte';
	import MessageThread from '$lib/components/viewer/MessageThread.svelte';
	import type { SessionWithProject, MessageRow } from '$lib/types/db';

	let session: SessionWithProject | null = $state(null);
	let messages: MessageRow[] = $state([]);
	let loading = $state(true);
	let error = $state('');

	onMount(async () => {
		const sessionId = page.params.sessionId;
		try {
			const [s, m] = await Promise.all([
				getSession(sessionId),
				getSessionMessages({ sessionId, limit: 500 })
			]);
			if (!s) {
				error = 'Session not found';
			} else {
				session = s;
				messages = m.messages;
			}
		} catch (e) {
			error = `Failed to load conversation: ${e}`;
		} finally {
			loading = false;
		}
	});
</script>

{#if loading}
	<div class="flex items-center justify-center h-full">
		<p class="text-sm text-muted-foreground">Loading conversation...</p>
	</div>
{:else if error}
	<div class="flex items-center justify-center h-full">
		<p class="text-sm text-destructive">{error}</p>
	</div>
{:else if session}
	<div class="flex flex-col h-full">
		<SessionHeader {session} />
		<MessageThread {messages} />
	</div>
{/if}
