// web/src/components/conversations/session-list.tsx
"use client";

import Link from "next/link";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ResumeButton } from "./resume-button";
import type { SessionWithProject } from "@/types/db";

function formatDate(dateStr: string | null): string {
  if (!dateStr) return "-";
  return new Date(dateStr).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

function formatSize(bytes: number | null): string {
  if (!bytes) return "-";
  if (bytes >= 1_048_576) return `${(bytes / 1_048_576).toFixed(1)} MB`;
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${bytes} B`;
}

export function SessionList({
  sessions,
  total,
  page,
  pageSize,
}: {
  sessions: SessionWithProject[];
  total: number;
  page: number;
  pageSize: number;
}) {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const totalPages = Math.ceil(total / pageSize);

  function goToPage(p: number) {
    const params = new URLSearchParams(searchParams.toString());
    params.set("page", p.toString());
    router.push(`${pathname}?${params.toString()}`);
  }

  return (
    <div>
      <div className="text-xs text-muted-foreground mb-2">
        {total} conversation{total !== 1 ? "s" : ""}
      </div>
      <div className="border rounded-lg divide-y">
        {sessions.map((s) => (
          <div
            key={s.id}
            className="flex items-center gap-3 px-4 py-3 hover:bg-accent/50 transition-colors"
          >
            <Link
              href={`/conversations/${s.id}`}
              className="flex-1 min-w-0"
            >
              <p className="text-sm font-medium truncate">
                {s.custom_title || s.first_prompt || s.id}
              </p>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-xs text-muted-foreground">
                  {s.project_display_name}
                </span>
                {s.git_branch && (
                  <Badge variant="outline" className="text-[10px] py-0">
                    {s.git_branch}
                  </Badge>
                )}
              </div>
            </Link>
            <div className="flex items-center gap-3 shrink-0 text-xs text-muted-foreground">
              {s.model && (
                <Badge variant="secondary" className="text-[10px] font-normal">
                  {s.model.replace("claude-", "").split("-").slice(0, 2).join("-")}
                </Badge>
              )}
              <span className="w-12 text-right" title="Messages">
                {s.message_count}
              </span>
              <span className="w-14 text-right" title="Tokens">
                {formatTokens(s.total_input_tokens + s.total_output_tokens)}
              </span>
              <span className="w-14 text-right" title="Cost">
                ${s.estimated_cost_usd.toFixed(2)}
              </span>
              <span className="w-24 text-right" title="Modified">
                {formatDate(s.modified_at)}
              </span>
              <ResumeButton sessionId={s.id} />
            </div>
          </div>
        ))}
        {sessions.length === 0 && (
          <div className="py-8 text-center text-sm text-muted-foreground">
            No conversations match your filters.
          </div>
        )}
      </div>
      {totalPages > 1 && (
        <div className="flex justify-center gap-2 mt-4">
          <Button
            variant="outline"
            size="sm"
            onClick={() => goToPage(page - 1)}
            disabled={page <= 1}
          >
            Previous
          </Button>
          <span className="text-sm self-center text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={() => goToPage(page + 1)}
            disabled={page >= totalPages}
          >
            Next
          </Button>
        </div>
      )}
    </div>
  );
}

// src/lib/components/conversations/SessionList.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import { SvelteURLSearchParams } from 'svelte/reactivity';
	import { formatDate, formatTokens } from '$lib/utils';
	import { renameSession } from '$lib/api/sessions';
	import ResumeButton from './ResumeButton.svelte';
	import OpenInButton from './OpenInButton.svelte';
	import type { SessionWithProject } from '$lib/types/db';

	let editingId = $state<string | null>(null);
	let editValue = $state('');

	let clickTimer: ReturnType<typeof setTimeout> | undefined;

	function startRename(s: SessionWithProject) {
		editingId = s.id;
		editValue = s.custom_title || s.first_prompt || '';
		setTimeout(() => {
			const input = document.getElementById(`rename-${s.id}`) as HTMLInputElement;
			input?.select();
		}, 0);
	}

	function handleTitleClick(e: MouseEvent, s: SessionWithProject) {
		if (e.metaKey || e.ctrlKey || e.shiftKey) return;
		e.preventDefault();
		e.stopPropagation();
		clearTimeout(clickTimer);
		clickTimer = setTimeout(() => {
			goto(resolve('/conversations/[sessionId]', { sessionId: s.id }));
		}, 300);
	}

	function handleTitleDblClick(e: MouseEvent, s: SessionWithProject) {
		e.preventDefault();
		e.stopPropagation();
		clearTimeout(clickTimer);
		startRename(s);
	}

	async function saveRename(s: SessionWithProject) {
		const trimmed = editValue.trim();
		if (!trimmed || trimmed === s.custom_title) {
			editingId = null;
			return;
		}
		try {
			await renameSession(s.id, trimmed);
			s.custom_title = trimmed;
		} catch (err) {
			console.error('Failed to rename:', err);
		}
		editingId = null;
	}

	function onRenameKeydown(e: KeyboardEvent, s: SessionWithProject) {
		if (e.key === 'Enter') {
			e.preventDefault();
			saveRename(s);
		} else if (e.key === 'Escape') {
			editingId = null;
		}
	}

	let {
		sessions,
		total,
		currentPage,
		pageSize
	}: {
		sessions: SessionWithProject[];
		total: number;
		currentPage: number;
		pageSize: number;
	} = $props();

	let totalPages = $derived(Math.ceil(total / pageSize));

	function shortModel(model: string | null): string {
		if (!model) return '';
		return model.replace('claude-', '').split('-').slice(0, 2).join('-');
	}

	function goToPage(p: number) {
		const params = new SvelteURLSearchParams(page.url.searchParams.toString());
		params.set('page', p.toString());
		goto(resolve(`${page.url.pathname}?${params.toString()}`));
	}
</script>

<div>
	<div class="text-muted-foreground mb-2 text-xs">
		{total} conversation{total !== 1 ? 's' : ''}
	</div>
	<div class="divide-y rounded-lg border">
		{#each sessions as s (s.id)}
			<div class="hover:bg-accent/50 flex items-center gap-3 px-4 py-3 transition-colors">
				<a href={resolve('/conversations/[sessionId]', { sessionId: s.id })} class="group/row min-w-0 flex-1">
					{#if editingId === s.id}
						<input
							id="rename-{s.id}"
							bind:value={editValue}
							onkeydown={(e) => onRenameKeydown(e, s)}
							onblur={() => saveRename(s)}
							onclick={(e) => e.preventDefault()}
							class="border-primary w-full border-b-2 bg-transparent px-0 py-0.5 text-sm font-medium outline-none"
						/>
					{:else}
						<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
						<p
							class="cursor-pointer truncate text-sm font-medium"
							onclick={(e) => handleTitleClick(e, s)}
							ondblclick={(e) => handleTitleDblClick(e, s)}
							onkeydown={(e) => {
								if (e.key === 'F2') {
									e.preventDefault();
									startRename(s);
								}
							}}
							title="Double-click to rename"
						>
							{s.custom_title || s.first_prompt || s.id}
						</p>
					{/if}
					<div class="mt-1 flex items-center gap-2">
						<span class="text-muted-foreground text-xs">
							{s.project_display_name}
						</span>
						{#if s.git_branch}
							<span
								class="text-muted-foreground inline-flex items-center rounded-full border px-2 py-0 text-[10px]"
							>
								{s.git_branch}
							</span>
						{/if}
					</div>
				</a>
				<div class="text-muted-foreground flex shrink-0 items-center gap-3 text-xs">
					{#if s.model}
						<span
							class="bg-secondary inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-normal"
						>
							{shortModel(s.model)}
						</span>
					{/if}
					<span class="w-12 text-right" title="Messages">{s.message_count}</span>
					<span class="w-14 text-right" title="Tokens"
						>{formatTokens(
							s.total_input_tokens +
								s.total_output_tokens +
								s.total_cache_creation_tokens +
								s.total_cache_read_tokens
						)}</span
					>
					<span class="w-14 text-right" title="Cost">${s.estimated_cost_usd.toFixed(2)}</span>
					<span class="w-24 text-right" title="Modified">{formatDate(s.modified_at)}</span>
					<OpenInButton sessionId={s.id} cwd={s.cwd} projectPath={s.project_path} />
					<ResumeButton sessionId={s.id} />
				</div>
			</div>
		{/each}
		{#if sessions.length === 0}
			<div class="text-muted-foreground py-8 text-center text-sm">No conversations match your filters.</div>
		{/if}
	</div>
	{#if totalPages > 1}
		<div class="mt-4 flex justify-center gap-2">
			<button
				class="border-input bg-background hover:bg-accent h-8 rounded-md border px-3 text-sm disabled:opacity-50"
				onclick={() => goToPage(currentPage - 1)}
				disabled={currentPage <= 1}
			>
				Previous
			</button>
			<span class="text-muted-foreground self-center text-sm">
				Page {currentPage} of {totalPages}
			</span>
			<button
				class="border-input bg-background hover:bg-accent h-8 rounded-md border px-3 text-sm disabled:opacity-50"
				onclick={() => goToPage(currentPage + 1)}
				disabled={currentPage >= totalPages}
			>
				Next
			</button>
		</div>
	{/if}
</div>
