// web/src/app/conversations/page.tsx
import { getSessions, getFilterOptions } from "@/lib/actions/sessions";
import { SessionList } from "@/components/conversations/session-list";
import { FilterPanel } from "@/components/conversations/filter-panel";

interface Props {
  searchParams: Promise<Record<string, string | undefined>>;
}

export default async function ConversationsPage({ searchParams }: Props) {
  const params = await searchParams;
  const page = parseInt(params.page || "1", 10);
  const pageSize = 30;

  const [result, filterOptions] = await Promise.all([
    getSessions({
      projectId: params.project ? parseInt(params.project, 10) : undefined,
      gitBranch: params.branch || undefined,
      model: params.model || undefined,
      search: params.q || undefined,
      sortBy: params.sort || "modified_at",
      sortDir: (params.dir as "asc" | "desc") || "desc",
      page,
      pageSize,
    }),
    getFilterOptions(),
  ]);

  return (
    <div className="p-6 space-y-4 max-w-7xl">
      <h2 className="text-xl font-semibold">Conversations</h2>
      <FilterPanel options={filterOptions} />
      <SessionList
        sessions={result.sessions}
        total={result.total}
        page={page}
        pageSize={pageSize}
      />
    </div>
  );
}

// src/routes/conversations/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { getSessions, getFilterOptions } from '$lib/api/sessions';
	import FilterPanel from '$lib/components/conversations/FilterPanel.svelte';
	import SessionList from '$lib/components/conversations/SessionList.svelte';
	import type { SessionWithProject, FilterOptions } from '$lib/types/db';

	let sessions: SessionWithProject[] = $state([]);
	let total = $state(0);
	let currentPage = $state(1);
	let pageSize = $state(30);
	let options: FilterOptions | null = $state(null);
	let loading = $state(true);

	async function loadData() {
		loading = true;
		try {
			const params = page.url.searchParams;
			const projectId = params.get('project') ? Number(params.get('project')) : undefined;
			const model = params.get('model') || undefined;
			const search = params.get('q') || undefined;
			const sortBy = params.get('sort') || 'modified_at';
			const pg = params.get('page') ? Number(params.get('page')) : 1;

			const [sessionsResult, filterOptions] = await Promise.all([
				getSessions({ projectId, model, search, sortBy, page: pg, pageSize: 30 }),
				options ? Promise.resolve(options) : getFilterOptions()
			]);

			sessions = sessionsResult.sessions;
			total = sessionsResult.total;
			currentPage = sessionsResult.page;
			pageSize = sessionsResult.pageSize;
			options = filterOptions;
		} catch (e) {
			console.error('Failed to load conversations:', e);
		} finally {
			loading = false;
		}
	}

	onMount(() => loadData());

	// Re-fetch when URL params change
	$effect(() => {
		// Access searchParams to track changes
		page.url.searchParams.toString();
		loadData();
	});
</script>

<div class="p-6 space-y-4 max-w-7xl">
	<h2 class="text-xl font-semibold">Conversations</h2>

	{#if options}
		<FilterPanel {options} />
	{/if}

	{#if loading && sessions.length === 0}
		<div class="space-y-2">
			{#each Array(5) as _}
				<div class="h-16 rounded-lg border animate-pulse"></div>
			{/each}
		</div>
	{:else}
		<SessionList {sessions} {total} {currentPage} {pageSize} />
	{/if}
</div>
